apiVersion: apps/v1
kind: Deployment
metadata:
  name: manila-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  annotations:
    config.openshift.io/inject-proxy: manila-csi-driver-operator
    storage.openshift.io/remove-from: guest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manila-csi-driver-operator
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        name: manila-csi-driver-operator
    spec:
      containers:
      - args:
        - start
        - -v=${LOG_LEVEL}
        env:
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: NFS_DRIVER_IMAGE
          value: ${NFS_DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: SNAPSHOTTER_IMAGE
          value: ${SNAPSHOTTER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: ${KUBE_RBAC_PROXY_IMAGE}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: manila-csi-driver-operator
        volumeMounts:
        - name: cloud-credentials
          mountPath: /etc/openstack
          readOnly: true
        # NOTE(stephenfin): This volumes definiton for this mount varies
        # between standalone and hypershift configurations, thus it is defined
        # in overlay patches
        # TODO(stephenfin): Remove in 4.20
        - name: legacy-cacert
          mountPath: /etc/openstack-ca
          readOnly: true
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      priorityClassName: system-cluster-critical
      serviceAccountName: manila-csi-driver-operator
      volumes:
      - name: cloud-credentials
        projected:
          sources:
            - secret:
                name: openstack-cloud-credentials
                items:
                - key: cacert
                  path: ca.crt
                optional: true
            - secret:
                name: openstack-cloud-credentials
                items:
                - key: clouds.yaml
                  path: clouds.yaml
      - name: tmp
        emptyDir:
          medium: Memory
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
