apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: manila-csi-drivers
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  secretRef:
    name: manila-cloud-credentials
    namespace: openshift-manila-csi-driver
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
